routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CropImageController;
use App\Http\Controllers\PagesController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/dashboard', 'PagesController@index');
Route::get('/', 'PagesController@index');
Route::get('/theo', 'PagesController@theo');
Route::get('/test', 'PagesController@test');
Route::get('/register/{role}', 'Auth\RegisterController@showRegister');

Route::resource('livres', 'LivresController');
Route::resource('livewire','LivewireController');
Route::post('/buy/{livre}', 'LivresController@buy');
Route::get('/wishlist', 'LivresController@wishlist');
Route::get('/sell', 'LivresController@sell');
Route::get('/table', 'TableController@table');
Route::get('/catalogue', 'LivresController@catalogue');
Route::resource('maison', 'MaisonController');




// Demo routes
Route::get('/datatables', 'PagesController@datatables');
Route::get('/ktdatatables', 'PagesController@ktDatatables');
Route::get('/select2', 'PagesController@select2');
Route::get('/jquerymask', 'PagesController@jQueryMask');
Route::get('/icons/custom-icons', 'PagesController@customIcons');
Route::get('/icons/flaticon', 'PagesController@flaticon');
Route::get('/icons/fontawesome', 'PagesController@fontawesome');
Route::get('/icons/lineawesome', 'PagesController@lineawesome');
Route::get('/icons/socicons', 'PagesController@socicons');
Route::get('/icons/svg', 'PagesController@svg');

// Quick search dummy route to display html elements in search dropdown (header search)
Route::get('/quick-search', 'PagesController@quickSearch')->name('quick-search');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/catalogue.blade.php
@extends('layout.default')
@section('styles')
@livewireStyles
<style>
    table
{
    border-collapse: collapse;
}
td, th /* Mettre une bordure sur les td ET les th */
{
    border: 1px solid black;
}
</style>
@endsection
@section('content')
<div class="card card-custom gutter-b">
    @livewire('livres-maison', ['type' => '1'])
</div>
@endsection
@section('scripts')
@livewireScripts
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layout.default')
<style>
    table
{
    border-collapse: collapse;
}
td, th /* Mettre une bordure sur les td ET les th */
{
    border: 1px solid black;
}
</style>
@section('content')
<div class="card card-custom gutter-b">
    <div class="card-header flex-wrap border-0 pt-6 pb-0">
        <div class="card-title">
            <h3 class="card-label">
                    Liste de vos livres
            </h3>
        </div>
        <button class="btn btn-primary font-weight-bolder text-uppercase px-9 py-4" onclick="window.location='{{ route('livewire.create') }}'">Créer un livre</button>
    </div>
    <div class="card-body">
        <div class="mb-7">
            <div class="row align-items-center">
                <div class="col-lg-9 col-xl-8">
                    <div class="row align-items-center">
                        <div class="col-md-4 my-2 my-md-0">
                            <div class="input-icon">
                                <input type="text" class="form-control" placeholder="Rechercher..."
                                    id="kt_datatable_search_query_campuse" />
                                <span>
                                    <i class="flaticon2-search-1 text-muted"></i>
                                </span>
                            </div>
                        </div>
                        <div class="col-lg-3 col-xl-4 mt-5 mt-lg-0">
                            <a href="#" class="btn btn-light-primary px-6 font-weight-bold">Ok</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <table class="datatable datatable-bordered datatable-head-custom" id="kt_datatable_campuse">
    <thead>
        <tr>
            <th title="Field #1">Titre</th>
            <th title="Field #2">Description</th>
            <th title="Field #3">Pages</th>
            <th title="Field #4">Suppression</th>
        </tr>
    </thead>
    <tbody>

        @foreach ($livres as $livre)
        <tr>
            <td><a href="/livres/{{$livre->id}}">{{ $livre->title }}</a></td>
            <td>{{ $livre->description }}</td>
            <td>{{ $livre->nb_page }}</td>
            <td>
                <form method="POST" action="/livres/{{$livre->id}}">
                    @csrf
                    @method('DELETE')
                    <button onclick="return confirm('Confirmer la suppression de {{$livre->title}} de la liste de vos livres ?')" type="submit" class="btn btn-sm btn-clean btn-icon" title="Supprimer">
                        <i class="flaticon-delete text-danger"></i>
                    </button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
</div>
</div>

@endsection
@section('scripts')
<script type="text/javascript" src="/custom/js/kt_datatable/html-table-campuse.js">
</script>
@endsection

resources/views/indexMaison.blade.php
@extends('layout.default')
@section('styles')
@livewireStyles
<style>
    table
{
    border-collapse: collapse;
}
td, th /* Mettre une bordure sur les td ET les th */
{
    border: 1px solid black;
}
</style>
@endsection
@section('content')
@livewire('maisons-table')



@endsection
@section('scripts')
@livewireScripts
@endsection

resources/views/livre.blade.php
@extends('layout.default')
@section('content')
@if(isset($livre))
<div class="card card-custom gutter-b">
    <div class="card-header flex-wrap border-0 pt-6 pb-0">
        <div class="card-title">
            <h3 class="card-label">
                Modifier le livre
            </h3>
        </div>
    </div>
    <div class="card-body">
    <form method="POST" action="/livres/{{$livre->id}}">
        @csrf
        @method('PUT')
        <div class="form-group row">
            <label class="col-xl-3 col-lg-3 col-form-label">Titre du livre :</label>
            <div class="col-lg-9 col-xl-6">
                <input class="form-control form-control-lg form-control-solid is-valid" id="title" name="title" type="text" placeholder="Titre" value="{{$livre->title}}">
                @error('title')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            </div>
        </div>
        <div class="form-group row">
            <label class="col-xl-3 col-lg-3 col-form-label">Description du livre :</label>
            <div class="col-lg-9 col-xl-6">
                <input class="form-control form-control-lg form-control-solid" name="description" type="text" placeholder="Description" value="{{$livre->description}}">
                @error('description')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            </div>
        </div>
        <div class="form-group row">
            <label class="col-xl-3 col-lg-3 col-form-label">Nombre de pages du livre :</label>
            <div class="col-lg-9 col-xl-6">
                <input class="form-control form-control-lg form-control-solid" name="nb_page" type="text" placeholder="Nombre de pages" value="{{$livre->nb_page}}">
                @error('nb_page')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            </div>
        </div>
        @if (Auth::user()->id == $livre->user_id)
        <div class="d-flex justify-content border-top mt-5 pt-10">
            <div class="mr-2">
        <button class="btn btn-warning font-weight-bolder text-uppercase px-9 py-4">↻ Mettre à jour</button>
            </form>
        </div>
        <div>
            <form method="POST" action="/livres/{{$livre->id}}">
                @csrf
                @method('DELETE')
                <button class="btn btn-danger font-weight-bolder text-uppercase px-9 py-4">✖ Supprimer</button>
            </form>
        </div>
        </div>
        @endif
    </div>
</div>
@else
<div class="card card-custom gutter-b">
    <div class="card-header flex-wrap border-0 pt-6 pb-0">
        <div class="card-title">
            <h3 class="card-label">
                Créer un livre
            </h3>
        </div>
    </div>
    <div class="card-body">
    <form method="POST" action={{ '/livres' }}>
        @csrf
        <div class="form-group row">
            <label class="col-xl-3 col-lg-3 col-form-label">Titre du livre :</label>
            <div class="col-lg-9 col-xl-6">
                <input class="form-control form-control-lg form-control-solid" id="titre_livre" name="title" type="text" placeholder="Titre" onkeydown="checkTitle()">
                @error('title')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            </div>
        </div>
        <div class="form-group row">
            <label class="col-xl-3 col-lg-3 col-form-label">Description du livre :</label>
            <div class="col-lg-9 col-xl-6">
                <input class="form-control form-control-lg form-control-solid" id="description_livre" name="description" type="text" placeholder="Description" onkeydown="checkDescription()">
                @error('description')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            </div>
        </div>
        <div class="form-group row">
            <label class="col-xl-3 col-lg-3 col-form-label">Nombre de pages du livre :</label>
            <div class="col-lg-9 col-xl-6">
                <input class="form-control form-control-lg form-control-solid" id="nb_pages_livre" name="nb_page" type="text" placeholder="Nombre de pages" onkeydown="checkPages()">
                @error('nb_page')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            </div>
        </div>
    <button class="btn btn-dark font-weight-bolder text-uppercase px-9 py-4" type="submit">Créer ce livre</button>
    </form>
    </div>
</div>
@endif
@endsection
@section('scripts')
<script>
    function checkTitle()
{
    setTimeout(function(){
    const length = $("#titre_livre").val().length;
    if(length>=6){
        $("#titre_livre").addClass("is-valid");
    }
    else{
        $("#titre_livre").removeClass("is-valid");
    }
    }, 20);
}

    function checkDescription()
{
    setTimeout(function(){
    const length = $("#description_livre").val().length;
    if(length>=10){
        $("#description_livre").addClass("is-valid");
    }
    else{
        $("#description_livre").removeClass("is-valid");
    }
    }, 20);
}

    function checkPages()
{
    setTimeout(function(){
    const length = $("#nb_pages_livre").val().length;
    let val = document.getElementById("nb_pages_livre").value
    let isnum = /^\d+$/.test(val);
    if(length==3){
        if(isnum){
        $("#nb_pages_livre").addClass("is-valid");
        }
        else{
        $("#nb_pages_livre").removeClass("is-valid");
        }
    }
    else{
        $("#nb_pages_livre").removeClass("is-valid");
    }
    }, 20);
}

</script>
@endsection

resources/views/sell.blade.php
@extends('layout.default')
@section('styles')
@livewireStyles
<style>
    table
{
    border-collapse: collapse;
}
td, th /* Mettre une bordure sur les td ET les th */
{
    border: 1px solid black;
}
</style>
@endsection
@section('content')
<div class="card card-custom gutter-b">
    @livewire('livres-maison', ['type' => '3'])
</div>

@endsection

@section('scripts')
@livewireScripts
@endsection

resources/views/showMaison.blade.php
@extends('layout.default')
@section('styles')
@livewireStyles
<style>
    table
{
    border-collapse: collapse;
}
td, th /* Mettre une bordure sur les td ET les th */
{
    border: 1px solid black;
}
</style>
@endsection
@section('content')
<div class="row">
    <div class="col-md-6">
        <div class="card card-custom gutter-b">
            <div class="card-header flex-wrap border-0 pt-6 pb-0">
                <div class="card-title">
                    <h3 class="card-label">
                        Informations sur la maison
                    </h3>
                </div>
            </div>
            <div class="card-body">
                @livewire('edit-maison', ['maison' => $maison])
            </div>
        </div>
    </div>
    <div class="col-md-6">
        @livewire('livres-maison', ['maison' => $maison])
    </div>
</div>
@endsection
@section('scripts')
@livewireScripts
@endsection

resources/views/theo.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    @livewireStyles
    <link rel="stylesheet" href="intlTelInput.css">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap">
    <link href="{{ asset('multiform.css') }}" rel="stylesheet" id="bootstrap">
    @extends('layout.default')
@section('content')
<body class="mt-5">
    <div class="container">
        <div class="text-center">
            Création école Edukare
        </div>
        <br>
        <livewire:wizard />
    </div>
</body>
@endsection
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
@livewireScripts
</html>

resources/views/view.blade.php
@extends('layout.default')
@section('content')
<div class="card card-custom gutter-b">
    <div class="card-header flex-wrap border-0 pt-6 pb-0">
        <div class="card-title">
            <h3 class="card-label">
                Informations sur le livre
            </h3>
        </div>
    </div>
    <div class="card-body">
            <p><b>Titre :</b> {{$livre->title}}</p>
            <p><b>Description :</b> {{$livre->description}}</p>
            <p><b>Nombre de pages :</b> {{$livre->nb_page}}</p>
            <div class="d-flex justify-content border-top mt-5 pt-10">
                <div class="mr-2">
                    <form method="POST" action="/buy/{{$livre->id}}">
                        @csrf
                    <button class="btn btn-success font-weight-bolder text-uppercase px-9 py-4">💳  Acheter</button>
                </form>
                </div>
        <div>
            <button class="btn btn-primary font-weight-bolder text-uppercase px-9 py-4" onclick="window.location='{{ route('livres.edit', ['livre' => $livre->id]) }}'">📝 Edit</button>
        </div>
            </div>
</div>
</div>
@endsection

resources/views/wishlist.blade.php
@extends('layout.default')
@section('styles')
@livewireStyles
<style>
    table
{
    border-collapse: collapse;
}
td, th /* Mettre une bordure sur les td ET les th */
{
    border: 1px solid black;
}
</style>
@endsection
@section('content')
<div class="card card-custom gutter-b">
    @livewire('livres-maison', ['type' => '2'])
</div>

@endsection

@section('scripts')
@livewireScripts
@endsection